name: unihitch_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  timeago: ^3.6.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.2
  pin_code_fields: ^8.0.1
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true